add logs

diff --git a/templates/Github/push-to-helm-chart-repo.yaml b/templates/Github/push-to-helm-chart-repo.yaml
--- a/templates/Github/push-to-helm-chart-repo.yaml
+++ b/templates/Github/push-to-helm-chart-repo.yaml
@@ -30,29 +30,37 @@ steps:
       echo "github User: ${githubUsername}"
       echo "github Email: ${githubEmail}"
 
+      echo "-------------------"
+
       git remote set-url origin $(git config remote.origin.url | sed "s/github.com/${githubUsername}:${githubToken}@github.com/g")
-      git config --global user.name "${githubUsername}"
-      git config --global user.email "${githubEmail}"
+      git config user.name "${githubUsername}"
+      git config user.email "${githubEmail}"
+      echo "-------------------"
 
       if [ -d "hmcts-charts" ]; then
+        echo "Remove Chart Directory"
         rm -rf hmcts-charts
       fi
+      echo "-------------------"
 
       while [ $COUNT -lt $RETRIES ]; do
         if git clone https://github.com/hmcts/hmcts-charts.git; then
+          echo "Cloned"
           COUNT=0
           break
         fi
-        COUNT=$(( $COUNT + 1))
+        COUNT=$(($COUNT + 1))
         if [ "$COUNT" = "$RETRIES" ]; then
           exit 1
         fi
+          echo "Failed to Cloned"
         sleep $DELAY
       done
+      echo "-------------------"
 
       if cd hmcts-charts; then
         if [ -d "${CHART_NAME}" ]; then
-          GIT_CHART_VERSION=$(helm inspect chart "${CHART_NAME}" | grep ^version | cut -d  ':' -f 2 | tr -d '[:space:]')
+          GIT_CHART_VERSION=$(helm inspect chart "${CHART_NAME}" | grep ^version | cut -d ':' -f 2 | tr -d '[:space:]')
           if [ "${GIT_CHART_VERSION}" = "${VERSION}" ]; then
             echo "No differences in the charts. Nothing to publish" 1>&2
             exit 0
@@ -60,33 +68,38 @@ steps:
         else
           echo "Chart version ${GIT_CHART_VERSION} not published to git yet" 1>&2
         fi
-        
+        echo "-------------------"
+
         if rsync -a --delete-after "${CHART_DIRECTORY}/" "./stable/${CHART_NAME}"; then
 
-          if [ -d ./stable/${CHART_NAME}/charts ]; then 
+          if [ -d ./stable/${CHART_NAME}/charts ]; then
             rm -rf ./stable/${CHART_NAME}/charts
-            if [[ $? -ne 0 ]];then
+            if [[ $? -ne 0 ]]; then
               echo "Unable to delete stable/${CHART_NAME}/charts directory" 1>&2
             fi
           fi
+          echo "-------------------"
 
-          if [ -e ./stable/${CHART_NAME}/Chart.lock ];then
+          if [ -e ./stable/${CHART_NAME}/Chart.lock ]; then
             rm -f ./stable/${CHART_NAME}/Chart.lock
-            if [[ $? -ne 0 ]];then
+            if [[ $? -ne 0 ]]; then
               echo "Unable to delete stable/${CHART_NAME}/Chart.lock " 1>&2
             fi
           fi
+          echo "-------------------"
 
-          if [ -e ./stable/${CHART_NAME}/requirements.lock ];then
+          if [ -e ./stable/${CHART_NAME}/requirements.lock ]; then
             rm -f ./stable/${CHART_NAME}/requirements.lock
-            if [[ $? -ne 0 ]];then
+            if [[ $? -ne 0 ]]; then
               echo "Unable to delete stable/${CHART_NAME}/requirements.lock " 1>&2
             fi
           fi
-  
+          echo "-------------------"
+
           git add "stable/${CHART_NAME}/"
           git commit -m "Auto-release ${CHART_NAME} ${VERSION} from ADO"
 
+          echo "-------------------"
           while [ $COUNT -lt $RETRIES ]; do
             git pull origin master
             if git push origin HEAD:master; then
@@ -96,21 +109,25 @@ steps:
             else
               echo "Failed to publish chart to git. Retry count $COUNT of $RETRIES"
             fi
-          COUNT=$(( $COUNT + 1))
-          if [ "$COUNT" = "$RETRIES" ]; then
-            exit 1
-          fi
-          sleep $DELAY
+            COUNT=$(($COUNT + 1))
+            if [ "$COUNT" = "$RETRIES" ]; then
+              exit 1
+            fi
+            sleep $DELAY
           done
+          echo "-------------------"
 
         else
           echo "Could not copy charts directory! Aborting" 1>&2
           exit 1
         fi
+        echo "-------------------"
       else
         echo "Could not change directory! Aborting" 1>&2
         exit 1
       fi
+      echo "-------------------"
+
 
     env:
       chartPath: ${{ parameters.chartPath }}
